### ISSUE TITLE
No Manual Calibration

### ISSUE THREAD

**Issue by yiyoMX** [arbox0/MedtronicUploader#14]
Hi arbox0, first of all thank you for these app, its the first time that I use it, I have an enlite sensor and the mmcommander setup, I intend to operate the enlite sensor without the pump or guardian, so I see that there is no manual calibration in the homepage of the app, only instant calibration, I already set manual calibration in the config options, what can I do?

**Comment by arbox0** [comment]
Instant calibration is a way to do "manual calibration", in fact if you have configured a glucometer in the uploader settings, when you do a calibration with your glucometer, and the enlite is next to the glucometer, after you tap on "instant calibration" the value of your last measurement should be "written" in the text field.

**Comment by yiyoMX** [comment]
Hi arbox0 thanks for your response, I've recompiled the app and enabled
manual calibration, because I thought instant calibration is used to input
the glucose value shown in the pump, which is already calibrated, since I
don't use the pump or the guardian (just the enlite sensor with your app) I
don't have access to this value. For what I understand the manual
calibration uses an algorithm to average the fist three values and the
instan calibration just inputs the first value, are you telling me that I
can use instant calibration with the number of my glucometer?

**Comment by sulkaharo** [comment]
Yes, you can enter the glucometer value into the Instant Calibration mode.

**Comment by yiyoMX** [comment]
Thanks Sulka, I'll be opening another thread for stability of the app when
there is no internet connection.
